---
- name: Deployment 
  hosts: server

  vars:
    path_web: /root
    path_pub_key: /root/.ssh/key
    pub_key_github: "{{ lookup('env', 'PUB_GITHUB_DEPLOY') }}"
    
  tasks:

    # - name: Generate the pair SSH private and public keys
    #   community.crypto.openssh_keypair:
    #     path: ~/.ssh/deploy

    # - name: Ensure .ssh directory exists.
    #   file:
    #     path: /var/www/.ssh
    #     state: directory
    #     mode: 0700


    - name: Create public file key
      copy:
        dest: "{{ path_pub_key }}"
        content: "{{ pub_key_github }}"
        mode: 0600

    # - name: Copy site contents
    #   copy:
    #     dest: "~/.ssh/deploy"
    #     src: "~/.ssh/id_rsa"
    #     owner: root
    #     group: root
    #     mode: 0755
    #     remote_src: yes

    - name: Git checkout
      ansible.builtin.git:
        repo: 'ssh://git@github.com/general03/deploy-ansible.git'
        dest: "{{ path_web }}"
        version: master
        # version: release-0.22
        accept_hostkey: yes
        key_file: "priv"