---
- name: Deployment 
  hosts: server
  roles:
    - role: pipenv

  vars:
    path_web: /root/rvb
    branch_to_deploy: master
    path_github_key: ~/.ssh/github
    personal_access_token_github: "{{ lookup('env', 'TOKEN_GITHUB') }}"
    
  tasks:
    - name: Ensure .ssh directory exists.
      file:
        path: ~/.ssh
        state: directory
        mode: 0700

    - name: Generate the pair SSH private and public keys for Github repo
      community.crypto.openssh_keypair:
        path: "{{ path_github_key }}"
      register: out_ssh_key

    - name: Create public file key in local
      copy:
        dest: "./github.pub"
        content: "{{ out_ssh_key.public_key }}"
        mode: 0600
      delegate_to: localhost

    # - name: Echo
    #   shell: |
    #     cat ./github.pub

    - name: Add a new read-only deploy key to a GitHub repository
      github_deploy_key:
        owner: "general03"
        repo: "deploy-ansible"
        name: "RVB_DEPLOY_KEY"
        key: "{{ lookup('file', './github.pub') }}"
        read_only: yes
        token: "{{ personal_access_token_github }}"
        
    - name: Git checkout
      git:
        repo: 'git@github.com:general03/deploy-ansible.git'
        dest: "{{ path_web }}"
        version: "{{ branch_to_deploy }}"
        accept_hostkey: yes
        key_file: "{{ path_github_key }}"