---
- name: Deployment 
  hosts: server

  vars:
    path_web: /root/rvb
    path_pub_key: /root/.ssh/key
    pub_key_github: "{{ lookup('env', 'PUB_GITHUB_DEPLOY') }}"
    personal_access_token_github: "{{ lookup('env', 'TOKEN_GITHUB') }}"
    
  tasks:

    - name: Ensure .ssh directory exists.
      file:
        path: ~/.ssh
        state: directory
        mode: 0700

    - name: Generate the pair SSH private and public keys for Github repo
      community.crypto.openssh_keypair:
        path: ~/.ssh/github
      register: out_ssh_key

    - name: Create public file key 
      copy:
        dest: "/root/.ssh/github.pub"
        content: "{{ out_ssh_key.public_key }}"
        mode: 0600

    # - name: Echo
    #   shell: |
    #     cat /root/.ssh/github.pub

    # - name: Create public file key 
    #   copy:
    #     dest: "{{ path_pub_key }}"
    #     content: "{{ pub_key_github }}"
    #     mode: 0600

    - name: Add a new read-only deploy key to a GitHub repository using basic authentication
      github_deploy_key:
        owner: "general03"
        repo: "deploy-ansible"
        name: "RVB_DEPLOY_KEY"
        key: "{{ lookup('file', '/root/.ssh/github.pub') }}"
        read_only: yes
        force: yes
        token: "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"
        
    # - name: Copy site contents
    #   copy:
    #     dest: "~/.ssh/deploy"
    #     src: "~/.ssh/id_rsa"
    #     owner: root
    #     group: root
    #     mode: 0755
    #     remote_src: yes

    - name: Git checkout
      ansible.builtin.git:
        repo: 'git@github.com:general03/deploy-ansible.git'
        dest: "{{ path_web }}"
        version: master
        # version: release-0.22
        accept_hostkey: yes
        key_file: "/root/.ssh/key.priv"

    # - name: Delete the .git folder
    #   file:
    #     path: "{{ path_web }}/.git"
    #     state: absent