image: python:3.8

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - python -m pip install --user ansible
    - export PATH=$PATH:~/.local/bin
    
    # -ansible -i deploy/ansible/inventory -m ping all
  script:
    - ansible-playbook deploy/ansible/deploy.yml -i deploy/ansible/inventory -vvvv
  
  only:
    - feature*

  tags:
    - docker
    - runner